spring:
  profiles:
    include:
    - mail
    - jwt
    - oauth
    - iamport
    - s3
    - database
  application:
    name: pilllaw
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  devtools:
    restart:
      enabled: true
      additional-paths:
      - src/main/java
      - src/main/resources
      - templates
    livereload:
      enabled: true
logging:
  level:
    root: 
      info
    jdbc.audit: WARN
    jdbc.connection: WARN
    jdbc.resultset: WARN
    jdbc.sqltiming: WARN
    com.zaxxer.hikari: WARN
    jdbc.sqlonly: WARN
    org.hibernate: WARN
app:
  domain: https://pilllaw.eeerrorcode.com
  # security:
  #   user:
  #     name: user1
  #     password: $2a$10$.JMquKR6u49eIKcQhbVLiuruKllowii8v0EdgET3qfyhljt/LOI3K #1234
  #     roles:
  #     - USER
